# Generated by Django 2.2 on 2019-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpipe', '0002_remove_emailaccount_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
